displayName=IRL XP
author=Therunner
support=https://github.com/mataeo-eh/GOK-IRL-XP
description=Turn real-world actions into banked XP and track it while you train
tags=bank,xp,experience,irl
version=
plugins=com.gokirlbankedxp.GokIrlBankedXpPlugin
build=standard
