displayName=GOK IRL Banked XP
author=Therunner
support=https://github.com/mataeo-eh/GOK-IRL-XP
description=Log IRL actions to bank XP to earn in game
tags=bank,xp,experience,irl
plugins=com.gokirlbankedxp.GokIrlBankedXpPlugin
